name: pile

# number of examples placed on each GPU. 
# will be overwritten if use_loadit is true.
batch_size: 4 

# shuffle buffer for data loader. 0 means no shuffle.
shuffle_buffer_size: 10000

# following settings chosen after
# some experimentation with a tiny model.
# may not be optimal for all machines, but
# hopefully with a reasonably sized model this will
# prevent dataloading from being the bottleneck.
dataloader_workers: 2

# if true, will use the loadit dataset in {loadit_path}
use_loadit: true
loadit_path: null

# if true, will manually shift labels to the left by one 
# and pad the last label by -100 during the training step.
# this is needed when using loadit dataset
shift_labels: false