defaults:
  - model: gpt
  - dataset: pile
  - optimizer: adamw
  - train
  - logging
  - checkpoint
  - experimental
  - test

# NOTE: since v2.0, the global random_seed is deprecated 
# and is replaced by specific seeds in each section.
random_seed: 42   # this controls the entire randomness during training