logging:
  wandb_project: null
  wandb_name: null
  wandb_runid: null
  wandb_expname: null

  # this will slow down computation a bit (I believe due to extra GPU/CPU communication),
  # but will log more stuff (like learning rates).
  # Still working on nice way to do this logging - we really should only incur one communication
  # round per iteration and I don't think the logging data should significantly impact it.
  log_callback_data: True

  # controls number of logs per sec.
  # set to inf for unlimited wandb logs.
  wandb_logs_per_sec: 10.0
  
  running_stats_window: 1000
