name: adamw
lr_config:    # TODO: move that to a sub-directory called lr_config, and instance with difference scheduler
  lr: 3e-4
  schedule: linear
  warmup: 5000
  max_steps: 50000
beta1: 0.9
beta2: 0.999
weight_decay: 0.1
debias_beta1: True
debias_beta2: True
