name: adam_base
defaults: 
  - lr_config: linear
lr_config:
  lr: 1e-3
beta1: 0.9
beta2: 0.999
use_nesterov: False
eps: 1e-8
weight_decay: 0.1
decouple_weight_decay: False
debias_beta1: True
debias_beta2: True
use_momentum: True
use_momentum_state: True
use_precond: True
use_precond_state: True