name: mango_v2
defaults:
  - lr_config: linear
lr_config:
  lr: 1.0

ns_steps: 6
eps: 1e-8
offset_beta: 0.95

# Configs that enable dictionary type

lr: 
  mat: 0.01
  embedding: 0.01
  head: 0.01
  attn_w: 0.01
  attn_b: 0.01
  vec_w: 0.01
  vec_b: 0.01

beta1:
  mat: 0.95
  embedding: 0.95
  head: 0.95
  attn_w: 0.95
  attn_b: 0.95
  vec_w: 0.95
  vec_b: 0.95

beta2:
  mat: 0.95
  embedding: 0.95
  head: 0.95
  attn_w: 0.95
  attn_b: 0.95
  vec_w: 0.95
  vec_b: 0.95

nesterov:
  mat: True
  embedding: True
  head: True
  attn_w: True
  attn_b: True
  vec_w: True
  vec_b: True

use_adamw:
  mat: False
  embedding: False
  head: False
  attn_w: False
  attn_b: False
  vec_w: False
  vec_b: False

normalize:
  mat: "ns"
  embedding: null
  head: "ns"
  attn_w: "ns"
  attn_b: "l2"
  vec_w: null
  vec_b: "l2"

scale_weight:
  mat: null #"op"
  embedding: null
  head: null #"op"
  attn_w: null #"op"
  attn_b: null #"l2"
  vec_w: null
  vec_b: null #"l2"

scale_power:
  mat: 1
  embedding: 1
  head: 1
  attn_w: 1
  attn_b: 1
  vec_w: 1
  vec_b: 1

scale_dim:
  mat: False
  embedding: False
  head: False
  attn_w: False
  attn_b: False
  vec_w: False
  vec_b: False

scale_clip_low: 1.0
scale_clip_high: null   # null defaults to jnp.inf

igt_scale: 0.0

# If true, clips max(1, sqrt(d_out/d_in))**0.5 
# to dimension scaling of NS normalization.
clip_ns: True

# If true, use sqrt(d); otherwise 
transpose_embedding: True

# log norms of each layer to wandb
visualize: False
