name: mango
defaults:
  - lr_config: linear
lr_config:
  lr: 1.0

momentum: 0.95
nesterov: True
ns_steps: 6
eps: 1e-8
beta2: 0.95
offset_beta: 0.99

lrs:
  mat: 0.05
  embedding: 0.05
  head: 0.05
  attn_w: 0.05
  attn_b: 0.05
  vec_w: 0.05
  vec_b: 0.05

normalizations:
  mat: "ns"
  embedding: "l2_col"
  head: "ns"
  attn_w: "ns"
  attn_b: "l2"
  vec_w: "inf_"
  vec_b: "l2"