name: muon_adamw
defaults:
  - lr_config: linear
lr_config:
  lr: 0.05

momentum: 0.95
nesterov: True
ns_steps: 6
eps: 1e-8
beta2: 0.95
offset_beta: 0.99

adam_lr: 3e-4
adam_beta1: 0.95
adam_beta2: 0.95
adam_eps: 1e-8
adam_wd: 0.0